{{- if ($.Values.global.deletePattern | default "0" | int | ne 1) }} {{- /* When a pattern is deleting applications should be removed */}}
{{- $namespace := print $.Values.global.pattern "-" $.Values.clusterGroup.name }}
{{- range .Values.clusterGroup.applications }}
{{- if . }} {{- /* Skip null applications */}}
{{- $projectName := coalesce .argoProject .project "default" -}} {{- /* Read argoProject if set, otherwise .project and otherwise set it to "default" */}}
{{- if .disabled }} {{- /* This allows us to null out an Application entry by specifying disabled: true in an override file */}}
{{- else }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
  labels:
    validatedpatterns.io/pattern: {{ $.Values.global.pattern }}
  {{- include "clustergroup.annotations" .annotations | nindent 2 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: {{ $.Values.clusterGroup.targetCluster }}
    namespace: {{ default $namespace .namespace }}
  project: {{ $projectName }}
  {{- if .chartVersion }} {{- /* if .chartVersion is set we assume this is a multisource app */}}
  sources:
    - repoURL: {{ $.Values.global.repoURL }}
      {{- /* We do not allow overriding the values with .targetRevision because when we use .targetRevision in a chart to specify the helm
             chart, that revision (e.g. 0.0.1) won't exist in the git tree. So here we simply always take the pattern's git branch/commit */}}
      targetRevision: {{ $.Values.global.targetRevision }}
      ref: patternref
    - repoURL: {{ coalesce .repoURL $.Values.global.multiSourceRepoUrl }}
      {{- if .chart }}
      chart: {{ .chart }}
      {{- else }}
      path: {{ .path }}
      {{- end }}{{- /* if .chart */}}
      targetRevision: {{ .chartVersion }}
      {{- if .plugin }}
      plugin: {{ .plugin | toPrettyJson }}
      {{- else }}
      helm:
        ignoreMissingValueFiles: true
        values: |
          extraParametersNested:
          {{- range $k, $v := $.Values.extraParametersNested }}
            {{ $k }}: {{ printf "%s" $v | quote }}
          {{- end }}
        valueFiles:
        {{- include "clustergroup.app.globalvalues.prefixedvaluefiles" $ | nindent 8 }}
        {{- include "clustergroup.sharedvaluefiles" (list . $) | nindent 8 }}
        {{- include "clustergroup.app.extravaluefiles" (list . $) | nindent 8 }}
        parameters:
          {{- include "clustergroup.app.globalvalues.helmparameters" $ | nindent 10 }}
          {{- range .extraHubClusterDomainFields }}
          - name: {{ . }}
            value: {{ $.Values.global.hubClusterDomain }}
          {{- end }}
          {{- range .extraLocalClusterDomainFields }}
          - name: {{ . }}
            value: {{ $.Values.global.localClusterDomain }}
          {{- end }}
          {{- range .extraRepoURLFields }}
          - name: {{ . }}
            value: $ARGOCD_APP_SOURCE_REPO_URL
          {{- end }}
          {{- range .extraTargetRevisionFields }}
          - name: {{ . }}
            value: $ARGOCD_APP_SOURCE_TARGET_REVISION
          {{- end }}
          {{- range .extraNamespaceFields }}
          - name: {{ . }}
            value: $ARGOCD_APP_NAMESPACE
          {{- end }}
          {{- range .extraPatternNameFields }}
          - name: {{ . }}
            value: {{ $.Values.global.pattern }}
          {{- end }}
          {{- range $k, $v := $.Values.extraParametersNested }}
          - name: {{ $k }}
            value: {{ printf "%s" $v | quote }}
          {{- end }}
          {{- range .overrides }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- if .forceString }}
            forceString: true
          {{- end }}
          {{- end }}{{- /* range .overrides */}}
        {{- if .fileParameters }}
        fileParameters:
        {{- range .fileParameters }}
          - name: {{ .name }}
            path: {{ .path }}
        {{- end }}
        {{- end }}{{- /* if .fileParameters */}}
      {{- end }}{{- /* if .plugin */}}
  {{- else }} {{- /* if .chartVersion */}}
  source:
    repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
    targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
    {{- if .chart }}
    chart: {{ .chart }}
    {{- else }}
    path: {{ .path }}
    {{- end }}{{- /* if .chart */}}
    {{- if .plugin }}
    plugin: {{ .plugin | toPrettyJson }}
    {{- else if not .kustomize }}
    helm:
      ignoreMissingValueFiles: true
      values: |
        extraParametersNested:
          {{- range $k, $v := $.Values.extraParametersNested }}
            {{ $k }}: {{ printf "%s" $v | quote }}
          {{- end }}
      valueFiles:
      {{- include "clustergroup.app.globalvalues.valuefiles" $ | nindent 6 }}
      {{- include "clustergroup.sharedvaluefiles" (list . $) | nindent 6 }}
      {{- include "clustergroup.app.extravaluefiles" (list . $) | nindent 6 }}
      parameters:
        {{- include "clustergroup.app.globalvalues.helmparameters" $ | nindent 8 }}
        {{- range .extraHubClusterDomainFields }}
        - name: {{ . }}
          value: {{ $.Values.global.hubClusterDomain }}
        {{- end }}
        {{- range .extraLocalClusterDomainFields }}
        - name: {{ . }}
          value: {{ $.Values.global.localClusterDomain }}
        {{- end }}
        {{- range .extraRepoURLFields }}
        - name: {{ . }}
          value: $ARGOCD_APP_SOURCE_REPO_URL
        {{- end }}
        {{- range .extraTargetRevisionFields }}
        - name: {{ . }}
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        {{- end }}
        {{- range .extraNamespaceFields }}
        - name: {{ . }}
          value: $ARGOCD_APP_NAMESPACE
        {{- end }}
        {{- range .extraPatternNameFields }}
        - name: {{ . }}
          value: {{ $.Values.global.pattern }}
        {{- end }}
        {{- range $k, $v := $.Values.extraParametersNested }}
        - name: {{ $k }}
          value: {{ printf "%s" $v | quote }}
        {{- end }}
        {{- range .overrides }}
        - name: {{ .name }}
          value: {{ .value | quote }}
          {{- if .forceString }}
          forceString: true
          {{- end }}
        {{- end }}{{- /* range .overrides */}}
      {{- if .fileParameters }}
      fileParameters:
      {{- range .fileParameters }}
        - name: {{ .name }}
          path: {{ .path }}
      {{- end }}{{- /* range .fileParameters */}}
      {{- end }}{{- /* if .fileParameters */}}
    {{- end }}{{- /* if .plugin */}}
  {{- end }}{{- /* if .chartVersion */}}
  {{- if .ignoreDifferences }}
  ignoreDifferences: {{ .ignoreDifferences | toPrettyJson }}
  {{- end }}
  {{ $syncpolicy := coalesce .syncPolicy $.Values.global.options.syncPolicy }}
  {{- if and (kindIs "string" $syncpolicy) (eq ($syncpolicy | lower) "manual") }}
  syncPolicy: null
  {{- else if and (kindIs "string" $syncpolicy) (eq ($syncpolicy | lower)  "automatic") }}
  syncPolicy:
    automated: {}
    retry:
      limit: {{ default 20 $.Values.global.options.applicationRetryLimit }}
  {{- else if $syncpolicy }}
  syncPolicy: {{ .syncPolicy | toPrettyJson }}
  {{- else }}
  syncPolicy:
    automated: {}
    retry:
      limit: {{ default 20 $.Values.global.options.applicationRetryLimit }}
  {{- end }}{{- /* .syncPolicy */}}
{{- end }}{{- /* if .disabled */}}
{{- end }}{{- /* if . (skip null applications) */}}
{{- end }}{{- /* range .Values.clusterGroup.applications */}}
{{- end }}{{- /* if ($.Values.global.deletePattern | default "0" | int | ne 1) */}}
